const MOCK_TOOL_ASSETS = [
  {
    id: "mock-2d-neon-pixel-city-pack",
    title: "Neon Pixel City Pack",
    slug: "neon-pixel-city-pack",
    type: "2D Asset Pack",
    category: "2D Assets",
    image: "aurora-drift",
    cardImage: "aurora-drift",
    carouselImage: "aurora-drift",
    shortDescription: "Layered city tileset with props and animated signage for cyberpunk platformers.",
    description:
      "A complete neon district tileset with storefront props, rooftop modules, and looping signage effects to ship richer 2D scenes faster.",
    useCase: "Build 2D cyberpunk districts, side-scroller streets, and mission hubs.",
    features: ["420 sprite slices", "Animated sign atlas", "Day/night palette variants"],
    techUsed: ["Aseprite", "Photoshop", "Unity"],
    price: "$24",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["aurora-drift", "aurora-drift-detail", "aurora-drift-ui"],
    tags: ["2D", "Pixel", "Environment"],
    publisher: "ShonStudio Labs",
    rating: 4.8,
    reviewCount: 137,
    fileSize: "186 MB",
    latestVersion: "1.3.0",
  },
  {
    id: "mock-2d-forest-adventure-sprite-bundle",
    title: "Forest Adventure Sprite Bundle",
    slug: "forest-adventure-sprite-bundle",
    type: "2D Asset Pack",
    category: "2D Assets",
    image: "aurora-drift",
    cardImage: "aurora-drift",
    carouselImage: "aurora-drift",
    shortDescription: "Hand-painted forests, ruins, and creature props for story-first 2D games.",
    description:
      "Curated biomes, decorative props, and atmospheric overlays to create magical forest routes with minimal art setup.",
    useCase: "Adventure platformers, learning games, and narrative 2D prototypes.",
    features: ["5 biome palettes", "Creature prop set", "Parallax-ready exports"],
    techUsed: ["Illustrator", "TexturePacker", "Unity"],
    price: "$19",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["aurora-drift", "aurora-drift-ui"],
    tags: ["2D", "Stylized", "Sprites"],
    publisher: "ShonStudio Labs",
    rating: 4.6,
    reviewCount: 89,
    fileSize: "142 MB",
    latestVersion: "1.1.2",
  },
  {
    id: "mock-2d-mobile-icons-starter",
    title: "Mobile Icons Starter",
    slug: "mobile-icons-starter",
    type: "2D UI Icons",
    category: "2D Assets",
    image: "mech-siege-hud",
    cardImage: "mech-siege-hud",
    carouselImage: "mech-siege-hud",
    shortDescription: "Clean, gameplay-ready icon set with progression and reward states.",
    description:
      "A broad icon library with status, currency, and progression symbols tuned for mobile readability and rapid implementation.",
    useCase: "Mobile HUDs, inventory menus, and progression screens.",
    features: ["340 SVG + PNG icons", "Rounded + sharp variants", "Naming convention map"],
    techUsed: ["Figma", "Illustrator"],
    price: "$12",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["mech-siege-hud", "mech-siege-mission"],
    tags: ["2D", "Icons", "Mobile"],
    publisher: "ShonStudio Labs",
    rating: 4.7,
    reviewCount: 62,
    fileSize: "34 MB",
    latestVersion: "1.0.8",
  },
  {
    id: "mock-3d-scifi-corridor-builder",
    title: "Sci-Fi Corridor Builder",
    slug: "scifi-corridor-builder",
    type: "3D Asset Pack",
    category: "3D Assets",
    image: "modular-environment-kit",
    cardImage: "modular-environment-kit",
    carouselImage: "modular-environment-kit",
    shortDescription: "Modular sci-fi hallway kit with trim sheets and lighting presets.",
    description:
      "Production-focused corridor modules, decals, and lighting presets designed for fast blockout-to-polish transitions.",
    useCase: "Shooter levels, station interiors, and mission-based environments.",
    features: ["95 modular meshes", "PBR material variants", "LOD and collision setup"],
    techUsed: ["Blender", "Substance 3D", "Unity"],
    price: "$39",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["modular-environment-kit", "pulse-xr-lab"],
    tags: ["3D", "Environment", "Sci-Fi"],
    publisher: "ShonStudio Labs",
    rating: 4.9,
    reviewCount: 214,
    fileSize: "512 MB",
    latestVersion: "2.0.1",
  },
  {
    id: "mock-3d-stylized-nature-kit",
    title: "Stylized Nature Kit",
    slug: "stylized-nature-kit",
    type: "3D Asset Pack",
    category: "3D Assets",
    image: "pulse-xr-lab",
    cardImage: "pulse-xr-lab",
    carouselImage: "pulse-xr-lab",
    shortDescription: "Trees, cliffs, and terrain props tuned for bright stylized worlds.",
    description:
      "A complete outdoor worldbuilding set including foliage clusters, path kits, rocks, and composition guides.",
    useCase: "Stylized RPG zones, casual exploration maps, and XR demos.",
    features: ["Foliage wind variants", "Terrain stamp set", "Color grading LUTs"],
    techUsed: ["Blender", "Unity URP"],
    price: "$34",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["pulse-xr-lab", "pulse-xr-interface"],
    tags: ["3D", "Stylized", "Nature"],
    publisher: "ShonStudio Labs",
    rating: 4.7,
    reviewCount: 121,
    fileSize: "428 MB",
    latestVersion: "1.5.4",
  },
  {
    id: "mock-3d-fantasy-village-creator",
    title: "Fantasy Village Creator",
    slug: "fantasy-village-creator",
    type: "3D Asset Pack",
    category: "3D Assets",
    image: "modular-environment-kit",
    cardImage: "modular-environment-kit",
    carouselImage: "modular-environment-kit",
    shortDescription: "Village architecture modules with market props and hero building pieces.",
    description:
      "Build complete medieval settlements with modular houses, street assets, and storytelling props in a single pack.",
    useCase: "Quest hubs, social zones, and cinematic fly-through scenes.",
    features: ["120 modular pieces", "Smart material IDs", "Marketplace prop kit"],
    techUsed: ["Maya", "Substance 3D", "Unity"],
    price: "$44",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["modular-environment-kit", "mech-siege-tactics"],
    tags: ["3D", "Fantasy", "Worldbuilding"],
    publisher: "ShonStudio Labs",
    rating: 4.8,
    reviewCount: 167,
    fileSize: "603 MB",
    latestVersion: "1.2.6",
  },
  {
    id: "mock-ui-rpg-hud-collection",
    title: "RPG HUD Collection",
    slug: "rpg-hud-collection",
    type: "UI Pack",
    category: "UI Packs",
    image: "mech-siege-hud",
    cardImage: "mech-siege-hud",
    carouselImage: "mech-siege-hud",
    shortDescription: "Inventory, quest, and combat UI screens with production naming conventions.",
    description:
      "An RPG-focused UI kit with modular bars, popup windows, and quest flow templates for rapid implementation.",
    useCase: "Action RPG prototypes, live-ops events, and interface overhauls.",
    features: ["Design tokens included", "HUD + menu variants", "Auto-layout Figma files"],
    techUsed: ["Figma", "Unity UI Toolkit"],
    price: "$29",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["mech-siege-hud", "mech-siege-mission"],
    tags: ["UI", "HUD", "RPG"],
    publisher: "ShonStudio Labs",
    rating: 4.9,
    reviewCount: 205,
    fileSize: "78 MB",
    latestVersion: "2.2.0",
  },
  {
    id: "mock-ui-casual-mobile-kit",
    title: "Casual Mobile UI Kit",
    slug: "casual-mobile-ui-kit",
    type: "UI Pack",
    category: "UI Packs",
    image: "aurora-drift-ui",
    cardImage: "aurora-drift-ui",
    carouselImage: "aurora-drift-ui",
    shortDescription: "Friendly mobile-first menu patterns, rewards, and onboarding flows.",
    description:
      "A colorful interface package for mobile games, including mission panels, shop cards, and reward dialogs.",
    useCase: "Hyper-casual, puzzle, and education products on mobile.",
    features: ["Onboarding flow templates", "Storefront widgets", "Reward animation guides"],
    techUsed: ["Figma", "Rive"],
    price: "$18",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["aurora-drift-ui", "aurora-drift"],
    tags: ["UI", "Mobile", "Casual"],
    publisher: "ShonStudio Labs",
    rating: 4.5,
    reviewCount: 73,
    fileSize: "52 MB",
    latestVersion: "1.4.3",
  },
  {
    id: "mock-ui-command-center-dash",
    title: "Command Center Dashboard UI",
    slug: "command-center-dashboard-ui",
    type: "UI Pack",
    category: "UI Packs",
    image: "mech-siege-hud",
    cardImage: "mech-siege-hud",
    carouselImage: "mech-siege-hud",
    shortDescription: "Tactical dashboard interfaces for simulations and mission control products.",
    description:
      "A high-density interface framework with graph widgets, status boards, and mission event components.",
    useCase: "Strategy games, ops simulations, and training dashboards.",
    features: ["Data table components", "Alert states", "Dark and light themes"],
    techUsed: ["Figma", "React", "Tailwind"],
    price: "$32",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["mech-siege-hud", "pulse-xr-interface"],
    tags: ["UI", "Dashboard", "Simulation"],
    publisher: "ShonStudio Labs",
    rating: 4.8,
    reviewCount: 96,
    fileSize: "91 MB",
    latestVersion: "1.8.1",
  },
  {
    id: "mock-vfx-spell-impact-suite",
    title: "Spell Impact VFX Suite",
    slug: "spell-impact-vfx-suite",
    type: "VFX Pack",
    category: "VFX & Particles",
    image: "pulse-xr-lab",
    cardImage: "pulse-xr-lab",
    carouselImage: "pulse-xr-lab",
    shortDescription: "Magic impact particles, trails, and hit flashes for fantasy combat.",
    description:
      "A cohesive spell VFX collection including projectile trails, impact bursts, aura loops, and timing presets.",
    useCase: "Action RPG combat prototypes and boss encounter polish.",
    features: ["60 particle prefabs", "HDR color variants", "Audio sync markers"],
    techUsed: ["Unity VFX Graph", "Shader Graph"],
    price: "$27",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["pulse-xr-lab", "pulse-xr-training"],
    tags: ["VFX", "Magic", "Combat"],
    publisher: "ShonStudio Labs",
    rating: 4.9,
    reviewCount: 183,
    fileSize: "212 MB",
    latestVersion: "2.1.0",
  },
  {
    id: "mock-vfx-weather-atmosphere-pack",
    title: "Weather Atmosphere Pack",
    slug: "weather-atmosphere-pack",
    type: "VFX Pack",
    category: "VFX & Particles",
    image: "audio-moodboard-library",
    cardImage: "audio-moodboard-library",
    carouselImage: "audio-moodboard-library",
    shortDescription: "Rain, fog, snow, and dust presets for cinematic environment mood.",
    description:
      "Weather and atmospheric effects designed to layer quickly into existing scenes without heavy setup overhead.",
    useCase: "Environmental storytelling and ambience polish across biomes.",
    features: ["Performance tiers", "Global weather controller", "Time-of-day hooks"],
    techUsed: ["Unity", "Shader Graph"],
    price: "$22",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["audio-moodboard-library", "aurora-drift"],
    tags: ["VFX", "Weather", "Atmosphere"],
    publisher: "ShonStudio Labs",
    rating: 4.6,
    reviewCount: 104,
    fileSize: "168 MB",
    latestVersion: "1.7.5",
  },
  {
    id: "mock-vfx-ui-feedback-burst-kit",
    title: "UI Feedback Burst Kit",
    slug: "ui-feedback-burst-kit",
    type: "VFX Pack",
    category: "VFX & Particles",
    image: "mech-siege-hud",
    cardImage: "mech-siege-hud",
    carouselImage: "mech-siege-hud",
    shortDescription: "Impact particles and glow cues tuned for button, reward, and upgrade feedback.",
    description:
      "Micro-VFX library for interface moments, including confirmations, rank-ups, and achievement reveal effects.",
    useCase: "Increase perceived responsiveness and delight in game UI flows.",
    features: ["UI-canvas-safe particles", "Color theme presets", "Screen-space support"],
    techUsed: ["Unity Particle System", "After Effects"],
    price: "$16",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["mech-siege-hud", "mech-siege-mission"],
    tags: ["VFX", "UI", "Feedback"],
    publisher: "ShonStudio Labs",
    rating: 4.7,
    reviewCount: 57,
    fileSize: "63 MB",
    latestVersion: "1.0.9",
  },
  {
    id: "mock-dev-save-system-pro",
    title: "Save System Pro",
    slug: "save-system-pro",
    type: "Dev Tool",
    category: "Dev Tools",
    image: "adaptive-dialogue-builder",
    cardImage: "adaptive-dialogue-builder",
    carouselImage: "adaptive-dialogue-builder",
    shortDescription: "Profile-based save framework with encryption, migration, and rollback safety.",
    description:
      "A robust persistence system for production games with schema migration helpers and cloud-save hooks.",
    useCase: "Ship stable save/load pipelines across live updates.",
    features: ["Versioned save schemas", "Auto backup snapshots", "Cloud sync adapters"],
    techUsed: ["C#", "Unity", ".NET"],
    price: "$35",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["adaptive-dialogue-builder", "pulse-xr-interface"],
    tags: ["Tool", "Save System", "Pipeline"],
    publisher: "ShonStudio Labs",
    rating: 4.9,
    reviewCount: 248,
    fileSize: "24 MB",
    latestVersion: "3.0.2",
  },
  {
    id: "mock-dev-quest-logic-toolkit",
    title: "Quest Logic Toolkit",
    slug: "quest-logic-toolkit",
    type: "Dev Tool",
    category: "Dev Tools",
    image: "adaptive-dialogue-builder",
    cardImage: "adaptive-dialogue-builder",
    carouselImage: "adaptive-dialogue-builder",
    shortDescription: "Node-based quest authoring system with branching paths and condition blocks.",
    description:
      "Design, validate, and export quest chains using a visual editor that reduces logic regressions during content updates.",
    useCase: "Narrative games, mission-based products, and live content operations.",
    features: ["Condition validator", "Branch conflict warnings", "JSON + CSV export"],
    techUsed: ["React", "Node.js", "Unity"],
    price: "$31",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["adaptive-dialogue-builder", "aurora-drift-ui"],
    tags: ["Tool", "Quest", "Narrative"],
    publisher: "ShonStudio Labs",
    rating: 4.8,
    reviewCount: 155,
    fileSize: "38 MB",
    latestVersion: "2.4.7",
  },
  {
    id: "mock-dev-localization-pipeline-manager",
    title: "Localization Pipeline Manager",
    slug: "localization-pipeline-manager",
    type: "Dev Tool",
    category: "Dev Tools",
    image: "audio-moodboard-library",
    cardImage: "audio-moodboard-library",
    carouselImage: "audio-moodboard-library",
    shortDescription: "String table manager with translator workflow and placeholder validation.",
    description:
      "Centralized localization toolkit to track keys, translation state, and integration QA for multilingual releases.",
    useCase: "Scale localization across regions while reducing missing-string bugs.",
    features: ["Glossary support", "CSV import/export", "Placeholder mismatch checks"],
    techUsed: ["React", "Node.js", "MongoDB"],
    price: "$28",
    ctaLabel: "Purchase",
    ctaUrl: "#",
    gallery: ["audio-moodboard-library", "pulse-xr-training"],
    tags: ["Tool", "Localization", "QA"],
    publisher: "ShonStudio Labs",
    rating: 4.7,
    reviewCount: 93,
    fileSize: "46 MB",
    latestVersion: "1.9.4",
  },
];

const toSlug = (value = "") =>
  value
    .toString()
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

export const mergeToolsWithMockAssets = (tools = []) => {
  const existingSlugs = new Set(
    tools
      .map((tool) => toSlug(tool.slug || tool.title || ""))
      .filter(Boolean),
  );

  const missingMockAssets = MOCK_TOOL_ASSETS.filter((asset) => !existingSlugs.has(toSlug(asset.slug)));

  return [...tools, ...missingMockAssets];
};

export { MOCK_TOOL_ASSETS };